version: "3.8"

services:
  nginx:
    build: ./nginx
    image: 014195623020.dkr.ecr.eu-north-1.amazonaws.com/nginx:${IMAGE_TAG}
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - node_js
    networks:
      - notes-app-nw

  node_js:
    build:
      context: .
      dockerfile: Dockerfile
    image: 014195623020.dkr.ecr.eu-north-1.amazonaws.com/node_js:${IMAGE_TAG}
    container_name: "nodejs_cont"
    ports:
      - "8000:8000"
    command: sh -c "node server.js"
    env_file:
      - ".env"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql:8
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
